title: My first Jekyll
author: Plamen Ivanov
email: paco.iwanow@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  First Jekyll static GitHub Pages. 

# social links
github_username:  k1lgor # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima